defmodule Mixchamb.Accounts.AnonymousUser do
  @moduledoc """
  An anonymous user — created on first visit, identified only by a
  signed session cookie. Idle users (no `last_active_at` activity for
  more than 24 hours) are reaped by `Mixchamb.Accounts.Sweeper`.
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "anonymous_users" do
    field :display_name, :string
    # Optional user-set nickname. The auto-generated `display_name`
    # stays the canonical identifier — UI shows the alias on top
    # with the anon name beneath. nil means "no alias set."
    field :alias, :string
    field :last_active_at, :utc_datetime
    # Last instrument the user picked in a music chamber.
    # Persisted so coming back to (or joining) a music chamber
    # doesn't reset everyone to drums. Stored as the same atom
    # string the wire uses (`"drums"`, `"keyboard"`, …); the LV
    # normalises against the @instruments allow-list on read.
    field :last_instrument, :string

    timestamps(type: :utc_datetime, updated_at: false)
  end

  @max_alias_length 32

  @doc """
  Changeset for creating a fresh anonymous user. The display name is
  generated by `Mixchamb.Accounts.NameGenerator`; callers should pass it
  in via attrs.
  """
  def creation_changeset(user, attrs) do
    user
    |> cast(attrs, [:display_name, :last_active_at])
    |> validate_required([:display_name])
    |> validate_length(:display_name, min: 1, max: 64)
  end

  @doc """
  Bumps `last_active_at`. Used by the `EnsureAnonUser` plug — debounced
  in the plug itself so we don't write on every request.
  """
  def touch_changeset(user, now) do
    change(user, last_active_at: now)
  end

  @doc """
  Sets the alias. Trims whitespace; blank → `nil` so users can
  clear an alias by submitting empty. Caps at #{@max_alias_length}
  chars.
  """
  def alias_changeset(user, attrs) do
    attrs = normalise_alias(attrs)

    user
    |> cast(attrs, [:alias])
    |> validate_length(:alias, max: @max_alias_length)
  end

  defp normalise_alias(attrs) do
    case attrs do
      %{"alias" => value} -> %{attrs | "alias" => blank_to_nil(value)}
      %{alias: value} -> %{attrs | alias: blank_to_nil(value)}
      _ -> attrs
    end
  end

  @doc """
  Records the user's most-recently-picked instrument. Persisted
  so a return visit to a music chamber lands them on their last
  pick rather than the default drums. Caller passes the atom-as-
  string (e.g. `"keyboard"`); the LV's allow-list normalisation
  happens on read.
  """
  def last_instrument_changeset(user, attrs) do
    user
    |> cast(attrs, [:last_instrument])
    |> validate_length(:last_instrument, max: 32)
  end

  defp blank_to_nil(nil), do: nil

  defp blank_to_nil(value) when is_binary(value) do
    case String.trim(value) do
      "" -> nil
      trimmed -> trimmed
    end
  end
end
